### ISSUE TITLE
Git workflows seem to fail due to missing certificate in secrets?

### ISSUE THREAD

**Issue by jbemmel** [akarneliuk/pygnmi#114]
https://github.com/akarneliuk/pygnmi/blob/3090d23ae32658026a244390a296f6ade01e9fb3/.github/workflows/ci.yaml#L20

**Comment by akarneliuk** [comment]
Hey @jbemmel ,
Thanks for contribution. That was an issue, but also there was one line in code, which required fixing. it is published now.
Best,
Anton
