### ISSUE TITLE
nornir example for subscribe stream mode

### ISSUE THREAD

**Issue by bpchoi** [akarneliuk/pygnmi#132]
Hello,

Can you have a example for nornir subscribe in stream mode?
I wonder how we can handle nornir task result for streamed data and streaming data on the fly if possible with nornir_pygnmi.

Regards,
Phil

**Comment by akarneliuk** [comment]
Hey @bpchoi,

We haven't build the telemetry subscription for Nornir. so far we support only capabilities, get and set. The reason for that is that I don't see much value: I doubt you would build telemetry collector using nornir, cause this is not what nornir is created for (it is created for doing finite request/response operations with some logical end, which is not the case for telemetry. For telemetry you make subscription and it stays open for as long as you receive data or heart bit, which can be days, weeks, months.

Best,
Anton
