### ISSUE TITLE
gNMI Master Arbitration Extension

### ISSUE THREAD

**Issue by AscendedEntity** [akarneliuk/pygnmi#143]
Hi, I am trying to make use of the master arbitration extension as described here:
https://github.com/openconfig/reference/blob/master/rpc/gnmi/gnmi-master-arbitration.md#32-setrequest-handling

However, I see that the extensions field is only present for telemetry and not for the set operation. Am I missing something or is support lacking here?

Thanks in advance.

**Comment by akarneliuk** [comment]
Solved by #146
