### ISSUE TITLE
Unable to connect to Unix domain socket

### ISSUE THREAD

**Issue by jbemmel** [akarneliuk/pygnmi#19]
At https://github.com/akarneliuk/pygnmi/blob/master/pygnmi/client.py#L61 the code assumes the target consists of a host:port string. 

I have an application that needs to connect locally, as in grpc.insecure_channel('unix:///some/socket/path')
I don't control the server path, so I cannot make it look like '/x/y/z:port'

**Comment by akarneliuk** [comment]
Hello @jbemmel ,

I believe you already have written the the path for that. I will try to test tomorrow and will let you know.

Out of curiosity, what is the application having such connectivity? OK if that is something private and you can't share.

Best,
Anton

**Comment by jbemmel** [comment]
On our Nokia SR Linux platform we use gNMI and Yang models as a system interface. An agent process running on the same platform can connect locally to the server, using a Unix socket avoids complications with network namespaces

**Comment by akarneliuk** [comment]
Hello @jbemmel ,

gotcha, thanks. Actually, waiting SRLinux 21.6 to have hands on public release finally :-)

BTW, in the release published yesterday your commit is added as well as `connect()` method. Could you please check if that works for you now?

Best,
Anton

**Comment by jbemmel** [comment]
Hi Anton,
I noticed the new connect() method - perhaps it would be better to have
__enter__(self) simply 'return self.connect()' ?

Regards,
Jeroen

**Comment by akarneliuk** [comment]
Hey @jbemmel ,

indeed, it looks simpler. Thanks for suggestion. I've just added this in the latest release `0.5.3`. Could you please test and let me know if that works for you.

Best,
Anton
