### ISSUE TITLE
Unable to receive streaming responses to Subscribe

### ISSUE THREAD

**Issue by jbemmel** [akarneliuk/pygnmi#21]
The 'Subscribe' request in 'stream' mode is (supposed to be) a long-lived subscription, returning responses from the server as they arrive. 

For some reason, the current implementation only seems to return the first response from the server - see https://github.com/akarneliuk/pygnmi/blob/master/pygnmi/client.py#L674

**Comment by akarneliuk** [comment]
Hey @jbemmel ,

It is returning all messages as this long living, if you follow the examples. See:
https://www.youtube.com/watch?v=-gQ1nkmClnw
https://www.youtube.com/watch?v=q2LUXeEgsDU

**Comment by jbemmel** [comment]
User error, exception caused a close()

Example code could use a try: except:
