### ISSUE TITLE
Support multithreaded clients

### ISSUE THREAD

**Issue by jbemmel** [akarneliuk/pygnmi#31]
As shown at https://stackoverflow.com/questions/52993976/grpc-python-support-multithreading-on-client-and-server/53090254, the suggested structure for multithreaded client applications:
1. global channel
2. per-thread stub instance

The way gNMIClient is currently structured, a channel and a stub are always allocated together.
Perhaps using Thread local storage (see e.g. https://www.bogotobogo.com/python/Multithread/python_multithreading_Thread_Local_Specific_Data.php) for the stub could work, together with separating channel instantiation from stub instantiation

Each method call could do 'getStub' which would create a thread-local instance if not already existing, on demand

**Comment by akarneliuk** [comment]
Hey @jbemmel ,

Thanks for the request. Could you please advise, which particular issue you are trying to solve, sir?

Looking at one of the shared links:
```
Also, since the channel is managed in C instead of Python, create multiple channels to the same server in the same process won't give you any performance advantage.
```

Best,
Anton
