### ISSUE TITLE
Telemetry streaming for specified time interval

### ISSUE THREAD

**Issue by mhnkrm** [akarneliuk/pygnmi#33]
Thanks for the Telemetry streaming library.
Telemetry streaming is not timebound.  Request to Support stream output for specified time and close the channel Gracefully.
Ex: Stream for 2 mins and close the channel gracefully

**Comment by akarneliuk** [comment]
Hello @mhnkrm ,

Thanks for your message. Can you please elaborate more a bit? provide the use case, or the output of code and device config?

Thanks,
Anton

**Comment by fperrin** [comment]
Hi @mhnkrm ,

With  PR #36 , you can read the updates from a stream request with a timeout. The API is a bit different, it looks like:

```python

        subscribe = {
            'subscription': [
                {
                    'path': 'openconfig-interfaces:interfaces/interface[name=1/1/c1/1]',
                    'mode': 'sample',
                    'sample_interval': 10000000000
                },
        }

        with gNMIclient(target=(host_entry["ip_address"], host_entry["port"]),
                        username=host_entry["username"], password=host_entry["password"], insecure=True) as gc:

            telemetry_stream = gc.subscribe_stream(subscribe=subscribe)
            for i in range(10):
                update = telemetry_stream.get_update(5)
                # ... do something with update

            # stop reading updates from the stream; the client connection is still useable for more get/set/subscribe requests
            telemetry_stream.close()
```

The argument to `get_update` is in seconds. It will throw a TimeoutError if the target does not send an update in the timeout given.

Does that solve your use-case?

**Comment by akarneliuk** [comment]
Thanks @fperrin
I created a high-level subscribe2 method, which calls then your methods, depending on argument type (stream, poll, once) automatically.
