### ISSUE TITLE
gNMI inactivity timeout?

### ISSUE THREAD

**Issue by andsouth44** [akarneliuk/pygnmi#45]
Hi Anton,
Are you aware of any inactivity timeouts in the code?
I have a gNMI subscription that can go for hours or days without producing a message and it appears disconnect/timeout after 2 hours. See below. 

This is a log from the Juniper router. It seems to send its last message at 20:26:22 and then receives a "call cancellation" at 22:26:42 (almost exactly 2 hours) from the gNMI client. 

This means that when the next message has to be sent from the Juniper, there is no gNMI subscription in place and the message is lost.

Sep 16 20:26:22 ProcessInPendingCall: Pushing tag for RPC: /gnmi.gNMI/Subscribe with tag id: request_1239761477into input pending call queue
Sep 16 22:26:42 ProcessInPendingCall: Processing pending call for RPC: /gnmi.gNMI/Subscribe with tag id: request_1239761477
Sep 16 22:26:42 ProcessInPendingCall: Received call cancellation for RPC: /gnmi.gNMI/Subscribe 
Sep 16 22:26:42 DelCallTag: Tag id request_1239761477 is removed from tag map for client nso
Sep 16 22:26:42 ProcessCall: Removing the cancelled call details for tag: request_261625440
Sep 16 22:26:42 ~GrpcCall:Invoking destructor
Sep 16 22:26:42 DecrRefCount: rpc request is /gnmi.gNMI/Subscribe
Sep 16 22:26:42 DecrRefCount: Reducing Ref count for Package gnmi 
Sep 16 22:26:42 ~GrpcToJapi:Invoking destrutor
Sep 16 22:26:42 DelCallTag: Tag id request_261625440 is removed from tag map for client nso
Sep 16 22:26:42 GetPeerConnInfo: getpeername for client fd 15 failed with error: Bad file descriptor
Sep 16 22:26:42 IsClientConnected: getpeername for the client ipv6:::ffff:xxxxxxxxx failed with error: Bad file descriptor
Sep 16 22:26:42 ~GrpcClientManager: Invoking destructor for client nso
Sep 16 22:26:42 ~GrpcClientManager:Termination sent to handler thread
Sep 16 22:26:42 DeleteChannel: Deleting entries in tag map for client ipv6:::ffff:xxxxxx:26647
Sep 16 22:26:42 ~GrpcClientManager: Cleaning out the channel map for client nso
Sep 16 22:26:42 GrpcHandleCall:Grpc handler cq is shutdown
Sep 16 22:26:42 DeleteChannel: Tag map is empty for client ipv6:::ffff:xxxxxx:26647
Sep 16 22:26:42 GrpcHandlerThreadCleanup:Executing grpc handler thread exit handler
Sep 16 22:26:42 DestroyClientInfo: peer ipv6:::ffff:xxxxxxx:26647 deleted from client map
Sep 16 22:26:45 jsd_config_read:Reading configuration...
Sep 16 22:26:45 readGrpcConfig:Inside ConfigManager::readGrpcConfig
Sep 16 22:26:45 readGrpcConfig:grpc ssl server knob is configured
Sep 16 22:26:45 readGrpcConfig: No change in certificate as crc before(32075) and after(32075) match
Sep 16 22:26:45 readGrpcConfig:mutual-authentication knob is configured
Sep 16 22:26:45 readGrpcConfig:request-response grpc is unchanged
Sep 16 22:26:45 readConfig:Notification service is not configured
Sep 16 22:26:45 readConfig:Notification service is not configured
Sep 16 22:26:45 jsd_sensor_config_read:jsd_sensor_config_read Invoked.
Sep 16 22:26:45 jsd_config_read_streaming_servers:No streaming servers available, delete all old servers.
Sep 16 22:26:45 jsd_config_read_export_profiles:No export profiles to read..
Sep 16 22:26:45 jsd_config_read_sensors:No sensors avaialble to read, delete all old sensors.
Sep 16 22:26:45 jsd_config_read_sensors:DAX walk failed for jsd_config_single_sensor.

**Comment by akarneliuk** [comment]
Hello @andsouth44 ,

Thanks for heads up. I must admit, we never tested having the gNMI session to stay open for so long period of time without any need. Could you please describe your use case, sir? I tend to thing, that there are some timers, which we can tweak if needed. 

In that regard, there will be some modifications in terms of inactivity timeout which @jbemmel  has recently made, and which will be in a new release we will publish shortly.

Best,
Anton

**Comment by andsouth44** [comment]
Hi Anton,
The use case is, I want to tigger an automation workflow based on a router interface becoming live, i.e. transitioning to operationally UP status.

**Comment by andsouth44** [comment]
Hi Anton,
I want to be able to detect and send a gNMI message when interfaces become operationally active on routers. I then use the message to invoke automation work flows. The interfaces may become active at any time and there may be very long quiet periods between events. Therefore I need the gNMI subscription to stay open indefinitely and I need a notification if the subscription is closed for any reason.
Maybe you can point me in the direction of the timers you think need to be tweaked and I can work on an enhancement myself?
Also, very interested to see the release - do you have a date?

Thanks
Andy

**Comment by jbemmel** [comment]
Hi Anton,

The timeout that is modified in my patch only applies to the initial
connect(), it does not affect this long idle connection use case.

We probably want to look at
https://github.com/grpc/grpc/blob/master/doc/keepalive.md for this
(defaults to 2 hours for the server side)

Regards,
Jeroen

**Comment by akarneliuk** [comment]
Ah, gotcha. So, there are two different things, then. Here we are talking about timeout of idle timeout for subscribe. Thinking out loud, there shall be a heartbit in your gnmi subscription. Could you please share your message, sir?

**Comment by andsouth44** [comment]
Thanks for the responses guys!
I have tried setting the heartbeat_interval in my gNMI subscriptions but I get a "not supported" error from the server - I confirmed neither Cisco or Juniper currently support the heartbeat_interval feature for gNMI.
So, this takes me back to my original question about inactivity timeouts; assuming I can't set the heartbeat_interval, then maybe I can extend or disable the timeout? However, from reading the links provided in this string it looks like the timeout I am running into is a TCP timeout. Is that correct?

**Comment by andsouth44** [comment]
Thanks, Jeroen!
This is very helpful.

**Comment by akarneliuk** [comment]
Hello @jbemmel ,
I've merged that, thank you. Will write some unit tests to see how it goes.

**Comment by akarneliuk** [comment]
Hey @jbemmel , @andsouth44 
the feature is added to the release `0.6.2`. Let me know if anything else is needed.
