### ISSUE TITLE
Stop publishing `dist` packages under git VCS

### ISSUE THREAD

**Issue by kamichal** [akarneliuk/pygnmi#50]
I see your git repository has `dist` directory containing various distributions of this package.
My advice is to stop doing this. There is no reason for keeping distributions under version control at all.
`pypi` is supposed to serve all the versions of this package, not git.
If you want to keep "old" versions - use tags, e.g. `git tag 0.6.3`. If you need to create an old package, you can check out the repository from a specific version and then just call `setup.py sdist` or `bdist_wheel`.

**Comment by akarneliuk** [comment]
Hey @kamichal ,
Thanks a lot for advise. 
Best,
Anton
