### ISSUE TITLE
ERROR:root:Conversion of gNMI paths to the Protobuf format failed on multiple key path

### ISSUE THREAD

**Issue by paunadeu** [akarneliuk/pygnmi#6]
Failed deleting this path:
`nokia-conf:configure/policy-options/prefix-list[name=PL_DDOS_MITIGATE]/prefix[ip-prefix=1.2.5.0/24][type=through]`

ip-prefix and type, both are required.

```
path = "nokia-conf:configure/policy-options/prefix-list[name=PL_DDOS_MITIGATE]/prefix[ip-prefix=1.2.5.0/24][type=through]"
gc.set(delete=[path])
```
returns:
`ERROR:root:Conversion of gNMI paths to the Protobuf format failed`

**Comment by paunadeu** [comment]
https://infocenter.nokia.com/public/7750SR160R4A/index.jsp?topic=%2Fcom.sr.system.mgmt%2Fhtml%2Ftelemetry-intro.html
8.2.1.4. Schema Paths
...
/a/b[key1=foo][key2=bar]/c[key1=*]

Assuming that nokia-conf:configure/policy-options/prefix-list[name=PL_DDOS_MITIGATE]/prefix[ip-prefix=1.2.5.0/24][type=through] is valid

We expect to delete:
    /configure policy-options prefix-list "PL_DDOS_MITIGATE" prefix 1.2.5.0/24 type through

**Comment by akarneliuk** [comment]
Hello Pau,

Thanks for raising issue. We found the example in the gNMI specification: https://github.com/openconfig/reference/blob/master/rpc/gnmi/gnmi-path-conventions.md

So we will fix that bug in the next release.

Thanks,
Anton

**Comment by akarneliuk** [comment]
Hello Pau,

We have updates the pyGNMI, please download the latest version (0.4.2). It contains the fix. The path now is build correctly:
```
$ python pygnmicli.py -t EOS425:6030 -u aaa -o get --gnmi-path nokia-conf:configure/policy-options/prefix-list[name=PL_DDOS_MITIGATE]/prefix[ip-prefix=1.2.5.0/24][type= through] -c cert.pem --print
The password is not defined.
gRPC password:
Doing get request to ('EOS425', 6030)...
gNMI request:
------------------------------------------------
path {
  origin: "nokia-conf"
  elem {
    name: "configure"
  }
  elem {
    name: "policy-options"
  }
  elem {
    name: "prefix-list"
    key {
      key: "name"
      value: "PL_DDOS_MITIGATE"
    }
  }
  elem {
    name: "prefix"
    key {
      key: "ip-prefix"
      value: "1.2.5.0/24"
    }
    key {
      key: "type"
      value: "through"
    }
  }
}

------------------------------------------------
```

Best,
Anton

**Comment by paunadeu** [comment]
Working!! :-)

Nice, thanks!! 👍
