### ISSUE TITLE
grpc.FutureTimeoutError Failure

### ISSUE THREAD

**Issue by KasinathAviz** [akarneliuk/pygnmi#94]
Hi team, 

Please find the gnmic capabilities of my NVDIA switch and the script . When I execute i got the below failure but gnmic manual execution is working.

Can you please help?

* gNMI enabled
* Port 9339
* mode using  "--skip-verify capabilities"

gnmic Capabilities:
=============
kasinath@npbsrv01:~$ gnmic -a <IP>:9339 -u cumulus -p aviz123 --skip-verify capabilities
gNMI version: 0.7.0
supported models:
  - nvidia-wjh, NVIDIA, 1.0.1
  - nvidia-if-ethernet-counters-ext, NVIDIA, 1.0.0
  - openconfig-interfaces, OpenConfig, 2.3.2
  - openconfig-if-ethernet, OpenConfig, 2.9.0
  - openconfig-if-ethernet-ext, OpenConfig, 0.1.1
  - openconfig-system, OpenConfig, 0.5.0
  - openconfig-lldp, OpenConfig, 0.2.1
  - openconfig-platform, OpenConfig, 0.13.0
supported encodings:
  - JSON

kasinath@npbsrv01:~$

gnmic Version:
===========
root@sqa01:/home/kasinath/Automation# gnmic version
version : 0.26.0
 commit : ba387ba
   date : 2022-06-29T06:52:10Z
 gitURL : https://github.com/karimra/gnmic
   docs : https://gnmic.kmrd.dev
root@sqa01:/home/kasinath/Automation#

Script:
======
root@sqa01:/home/kasinath/Automation# more test_gnmi.py
#!/usr/bin/env python3

# Modules
from pygnmi.client import gNMIclient

# Variables
host1 = {
        "ip_address": "<IP>",
        "port": 9339,
        "username": "cumulus",
        "password": "aviz123"
}

# Body

if __name__ == "__main__":
    with gNMIclient(target=(host1["ip_address"], host1["port"]), username=host1["username"], password=host1["password"], insecure=True) as
 gc:
        result = gc.capabilities()

        print(result)
root@sqa01:/home/kasinath/Automation#

Execution failure:
===============
root@sqa01:/home/kasinath/Automation# python3 test_gnmi.py
Traceback (most recent call last):
  File "test_gnmi.py", line 17, in <module>
    with gNMIclient(target=(host1["ip_address"], host1["port"]), username=host1["username"], password=host1["password"], insecure=True) as gc:
  File "/usr/local/lib/python3.8/dist-packages/pygnmi/client.py", line 103, in __enter__
    return self.connect()
  File "/usr/local/lib/python3.8/dist-packages/pygnmi/client.py", line 225, in connect
    self.wait_for_connect(timeout)
  File "/usr/local/lib/python3.8/dist-packages/pygnmi/client.py", line 235, in wait_for_connect
    grpc.channel_ready_future(self.__channel).result(timeout=timeout)
  File "/usr/local/lib/python3.8/dist-packages/grpc/_utilities.py", line 139, in result
    self._block(timeout)
  File "/usr/local/lib/python3.8/dist-packages/grpc/_utilities.py", line 85, in _block
    raise grpc.FutureTimeoutError()
grpc.FutureTimeoutError
root@sqa01:/home/kasinath/Automation#

pygnmi installation successful:
=======================
root@sqa01:/home/kasinath# pip install pygnmi
Collecting pygnmi
  Downloading pygnmi-0.8.8.tar.gz (30 kB)
Requirement already satisfied: cryptography in /usr/lib/python3/dist-packages (from pygnmi) (2.8)
Collecting dictdiffer
  Downloading dictdiffer-0.9.0-py2.py3-none-any.whl (16 kB)
Collecting grpcio
  Downloading grpcio-1.47.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.5 MB)
     |████████████████████████████████| 4.5 MB 39.9 MB/s
Collecting protobuf
  Downloading protobuf-4.21.5-cp37-abi3-manylinux2014_x86_64.whl (408 kB)
     |████████████████████████████████| 408 kB 41.2 MB/s
Requirement already satisfied: six>=1.5.2 in /usr/lib/python3/dist-packages (from grpcio->pygnmi) (1.14.0)
Building wheels for collected packages: pygnmi
  Building wheel for pygnmi (setup.py) ... done
  Created wheel for pygnmi: filename=pygnmi-0.8.8-py3-none-any.whl size=32744 sha256=5c388dfec571999d5975fcb12f22e2c99db55a56aaaca153d168930b3183d3b2
  Stored in directory: /root/.cache/pip/wheels/d5/56/76/e2698d9a887f61437c7e46940e75b062a022bff4608c6a7471
Successfully built pygnmi
Installing collected packages: dictdiffer, grpcio, protobuf, pygnmi
Successfully installed dictdiffer-0.9.0 grpcio-1.47.0 protobuf-4.21.5 pygnmi-0.8.8
root@sqa01:/home/kasinath#

Thanks
Kasi

**Comment by akarneliuk** [comment]
Hello @rkasinath ,

gRPC timeout failure means that `pygnmi` is not able to connect to the host. Here are a few consideration:
- `insecure=True` means that that gNMI is configured on the server (your network switch) in a way that it doesn't use encryption. That is not `--skip-verify`. If your host uses self-signed certificate, you shall use `skip_verify=True` instead. Refer to [the skip_verify demo](https://www.youtube.com/watch?v=-r4JbQBjVGU)
- You don't specify host, where are connecting to. You have "" instead of IP address of FQDN. Please, specify it, even if it is 127.0.0.1 or localhost. Connection to Unix socket is also supported, but you need to specify that as will.

Please, test and let me know.

Best,
Anton

**Comment by rkasinath** [comment]
Thanks Anton,

I am getting the below errors, but the manual gnmic is working fine.

* TSI_INTERNAL_ERROR
* in wait_for_connect

*pygnmi Version:*
***@***.***:/home/kasinath/Automation# pip show pygnmi
Name: pygnmi
Version: 0.8.8
Summary: Pure Python gNMI client to manage network functions and collect
telemetry.
Home-page: https://github.com/akarneliuk/pygnmi
Author: Anton Karneliuk
Author-email: ***@***.***
License: bsd-3-clause
Location: /usr/local/lib/python3.8/dist-packages
Requires: protobuf, cryptography, dictdiffer, grpcio
Required-by:
***@***.***:/home/kasinath/Automation#

*Manual:*

***@***.***:/home/kasinath/Automation# gnmic -a 10.4.5.77:9339 -u cumulus -p
admin --skip-verify capabilities

gNMI version: 0.7.0

supported models:

  - nvidia-wjh, NVIDIA, 1.0.1

  - nvidia-if-ethernet-counters-ext, NVIDIA, 1.0.0

  - openconfig-interfaces, OpenConfig, 2.3.2

  - openconfig-if-ethernet, OpenConfig, 2.9.0

  - openconfig-if-ethernet-ext, OpenConfig, 0.1.1

  - openconfig-system, OpenConfig, 0.5.0

  - openconfig-lldp, OpenConfig, 0.2.1

  - openconfig-platform, OpenConfig, 0.13.0

supported encodings:

  - JSON


*Script:*

#!/usr/bin/env python3


# Modules

from pygnmi.client import gNMIclient


# Variables

host1 = {

        "ip_address": "10.4.5.77",

        "port": 9339,

        "username": "cumulus",

        "password": "admin"

}


# Body


if __name__ == "__main__":

    with gNMIclient(target=(host1["ip_address"], host1["port"]),
username=host1["username"], password=host1["password"], skip_verify=True)
as gc:

        result = gc.capabilities()


        print(result)


*Failure Logs:*
***@***.***:/home/kasinath/Automation# python3 test_gnmi_cumulus.py
Cannot get Common Name: list index out of range
Cannot get Subject Alternative Names: No <ObjectIdentifier(oid=2.5.29.17,
name=subjectAltName)> extension was found
ssl_target_name_override is applied, should be used for testing only!
E0816 00:22:10.786982801 1170323 ssl_transport_security.cc:1702] Invalid
server name indication .
E0816 00:22:10.787061792 1170323 ssl_security_connector.cc:135] Handshaker
creation failed with error TSI_INTERNAL_ERROR.
E0816 00:22:11.786556923 1170322 ssl_transport_security.cc:1702] Invalid
server name indication .
E0816 00:22:11.786665398 1170322 ssl_security_connector.cc:135] Handshaker
creation failed with error TSI_INTERNAL_ERROR.
E0816 00:22:13.557512114 1170322 ssl_transport_security.cc:1702] Invalid
server name indication .
E0816 00:22:13.557568607 1170322 ssl_security_connector.cc:135] Handshaker
creation failed with error TSI_INTERNAL_ERROR.
Failed to setup gRPC channel, trying change cipher
E0816 00:22:16.224506856 1170322 ssl_transport_security.cc:1702] Invalid
server name indication .
E0816 00:22:16.224565928 1170322 ssl_security_connector.cc:135] Handshaker
creation failed with error TSI_INTERNAL_ERROR.
E0816 00:22:20.169553227 1170365 ssl_transport_security.cc:1702] Invalid
server name indication .
E0816 00:22:20.169639684 1170365 ssl_security_connector.cc:135] Handshaker
creation failed with error TSI_INTERNAL_ERROR.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pygnmi/client.py", line 235,
in wait_for_connect
    grpc.channel_ready_future(self.__channel).result(timeout=timeout)
  File "/usr/local/lib/python3.8/dist-packages/grpc/_utilities.py", line
139, in result
    self._block(timeout)
  File "/usr/local/lib/python3.8/dist-packages/grpc/_utilities.py", line
85, in _block
    raise grpc.FutureTimeoutError()
grpc.FutureTimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test_gnmi_cumulus.py", line 17, in <module>
    with gNMIclient(target=(host1["ip_address"], host1["port"]),
username=host1["username"], password=host1["password"], skip_verify=True)
as gc:
  File "/usr/local/lib/python3.8/dist-packages/pygnmi/client.py", line 103,
in __enter__
    return self.connect()
  File "/usr/local/lib/python3.8/dist-packages/pygnmi/client.py", line 225,
in connect
    self.wait_for_connect(timeout)
  File "/usr/local/lib/python3.8/dist-packages/pygnmi/client.py", line 243,
in wait_for_connect
    grpc.channel_ready_future(self.__channel).result(timeout=timeout)
  File "/usr/local/lib/python3.8/dist-packages/grpc/_utilities.py", line
139, in result
    self._block(timeout)
  File "/usr/local/lib/python3.8/dist-packages/grpc/_utilities.py", line
85, in _block
    raise grpc.FutureTimeoutError()
grpc.FutureTimeoutError
***@***.***:/home/kasinath/Automation#

Thanks
Kasi

**Comment by akarneliuk** [comment]
Hello @rkasinath ,
Thanks for sharing. can you please post here the certificate details? 
Best,
Anton

**Comment by rkasinath** [comment]
Hi Anton,

It`s a cumulus Linux switch MSN3700C. May I know which certificate details
you need and how to collect it?

Thanks
Kasi

**Comment by akarneliuk** [comment]
Hey @rkasinath ,

As thought as you have configured gNMI on Cumulus, you should know that. [Is that how you have enabled that](https://docs.nvidia.com/networking-ethernet-software/cumulus-netq-43/Manage-Configuration/Manage-Events-and-Notifications/gNMI-Streaming/)?

Best,
Anton

**Comment by rkasinath** [comment]
Hi Anton,

I have used the below config to enable gnmi not sure on the certificate. I
have an EOS switch, will do the same and test.



*Cumulus Config:===============*netq config add agent gnmi-enable true
netq config restart agent
netq config add agent opta-enable false
netq config add agent gnmi-port 9339

***@***.***:mgmt:~$ cat /etc/netq/netq.yml*
netq-agent:
  is-gnmi-enabled: *true*
  is-opta-enabled: *false*
netq-gnmi:
  gnmi_port: *9339*
***@***.***:mgmt:~$

Thanks
Kasi

**Comment by akarneliuk** [comment]
Thanks @rkasinath ,
The logs you shared is aligned with situation when certificate is strangely created (no CN, no SAR), which is raised in an issue #71 . We are looking into that, but having certificate with empty CN and empty SAR is generally bad idea.

**Comment by akarneliuk** [comment]
Hey @XioNoX ,

Thanks for your message. 

First thing, the argument `insecure=True` means that the gRPC channel is not encrypted (i.e., there is no certificate at all), whilst `skip_verify=True` means that the validation of SSL certificate is skipped provided your certificate has CN or SAN. As your certificate seems to have it, I'd test something like:
```python
from pygnmi.client import gNMIclient

host = ('server.example.org', '8080')

with gNMIclient(target=host, username='ayounsi', password='Password', skip_verify=True, debug=True) as gc:
     result = gc.capabilities()
     print(result)
```
Please, provide output.

In terms of providing more trace to the output, I don't see that much value from the perspective of using this library by end customers. The primary audience for the library is people who needs a Python tool to build automation with GNMI. The trace you have attached, as you can see, provides trace of C code. If you are not C developer, this data is simply useless. If you are C developer, then you can add the debugs in the way you have provided.

Best,
Anton

**Comment by XioNoX** [comment]
Thanks for your quick reply.

With what you suggested I'm getting:
```
ssl_target_name_override is applied, should be used for testing only!
GRPC Target
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
server.example.org:8080
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


GRPC Channel options
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
[('grpc.ssl_target_name_override', 'server.example.org'), ('grpc.ssl_target_name_override', 'server.example.org')]
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


E1215 08:53:00.842394719  489611 ssl_transport_security.cc:1501]       Handshake failed with fatal error SSL_ERROR_SSL: error:10000410:SSL routines:OPENSSL_internal:SSLV3_ALERT_HANDSHAKE_FAILURE.
E1215 08:53:01.845865761  489611 ssl_transport_security.cc:1501]       Handshake failed with fatal error SSL_ERROR_SSL: error:10000410:SSL routines:OPENSSL_internal:SSLV3_ALERT_HANDSHAKE_FAILURE.
E1215 08:53:03.639144350  489611 ssl_transport_security.cc:1501]       Handshake failed with fatal error SSL_ERROR_SSL: error:10000410:SSL routines:OPENSSL_internal:SSLV3_ALERT_HANDSHAKE_FAILURE.
Failed to setup gRPC channel, trying change cipher
E1215 08:53:06.145982185  489611 ssl_transport_security.cc:1501]       Handshake failed with fatal error SSL_ERROR_SSL: error:10000410:SSL routines:OPENSSL_internal:SSLV3_ALERT_HANDSHAKE_FAILURE.
E1215 08:53:10.592028112  489611 ssl_transport_security.cc:1501]       Handshake failed with fatal error SSL_ERROR_SSL: error:10000410:SSL routines:OPENSSL_internal:SSLV3_ALERT_HANDSHAKE_FAILURE.
Traceback (most recent call last):
  File "/home/xionox/Documents/Projects/Wikimedia-tinkering/restconf-testing/.venv/lib/python3.10/site-packages/pygnmi/client.py", line 237, in wait_for_connect
    grpc.channel_ready_future(self.__channel).result(timeout=timeout)
  File "/home/xionox/Documents/Projects/Wikimedia-tinkering/restconf-testing/.venv/lib/python3.10/site-packages/grpc/_utilities.py", line 151, in result
    self._block(timeout)
  File "/home/xionox/Documents/Projects/Wikimedia-tinkering/restconf-testing/.venv/lib/python3.10/site-packages/grpc/_utilities.py", line 97, in _block
    raise grpc.FutureTimeoutError()
grpc.FutureTimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xionox/Documents/Projects/Wikimedia-tinkering/restconf-testing/test.py", line 7, in <module>
    with gNMIclient(target=host, username='ayounsi', password='Password', skip_verify=True, debug=True) as gc:
  File "/home/xionox/Documents/Projects/Wikimedia-tinkering/restconf-testing/.venv/lib/python3.10/site-packages/pygnmi/client.py", line 103, in __enter__
    return self.connect()
  File "/home/xionox/Documents/Projects/Wikimedia-tinkering/restconf-testing/.venv/lib/python3.10/site-packages/pygnmi/client.py", line 225, in connect
    self.wait_for_connect(timeout)
  File "/home/xionox/Documents/Projects/Wikimedia-tinkering/restconf-testing/.venv/lib/python3.10/site-packages/pygnmi/client.py", line 245, in wait_for_connect
    grpc.channel_ready_future(self.__channel).result(timeout=timeout)
  File "/home/xionox/Documents/Projects/Wikimedia-tinkering/restconf-testing/.venv/lib/python3.10/site-packages/grpc/_utilities.py", line 151, in result
    self._block(timeout)
  File "/home/xionox/Documents/Projects/Wikimedia-tinkering/restconf-testing/.venv/lib/python3.10/site-packages/grpc/_utilities.py", line 97, in _block
    raise grpc.FutureTimeoutError()
grpc.FutureTimeoutError
```

I agree that the GRPC trace is too verbose :) However for at least this issue, adding `debug=True` doesn't add actionable indication on where the issue is. So my question was more around ways to provide _just enough_ logs to investigate the issue without having to bother you for further troubleshooting.

**Comment by XioNoX** [comment]
As additional data point, the same issue happen on a Junos vMX (also works fine with gnmic).

**Comment by akarneliuk** [comment]
Hey @XioNoX ,

I wonder how you generates Certificate for juniper, because there is a bunch of people who used pygnmi with Juniper already, and are doing so for more than a year and don't have any issues.
In terms of SONiC, i'm actually keen to test it. Which version of SONiC are using? is that VM? Is that Container? Is that real device? If the latter, is there a way I could get access to it?

Thanks,
Anton

**Comment by akarneliuk** [comment]
Hey @XioNoX , @KasinathAviz ,

First of all, happy new year. I've been able to get that working for SONiC (OCP version, but I believe it shall be working for Broadcom Enterprise version as well).

I have picked up the latest image here: https://sonic-net.github.io/SONiC/sonic_latest_images.html

Then:
Generate SS CA certificate and key:
```
admin@sonic:~$ sudo openssl req -x509 -newkey rsa:4096 -keyout /etc/sonic/telemetry/dsmsroot.key \
  -out /etc/sonic/telemetry/dsmsroot.cer -sha256 -days 365 -nodes -subj '/CN=lab-ca'
```

Generate CSR for server:
```
admin@sonic:~$ sudo openssl req -new -newkey rsa:4096 -nodes \
  -keyout /etc/sonic/telemetry/streamingtelemetryserver.key -out /etc/sonic/telemetry/streamingtelemetryserver.csr \
  -subj "/CN=dev-pygnmi-sonic-003"
```

Sign CSR with SS CA:
```
admin@sonic:~$ sudo openssl x509 -req -in /etc/sonic/telemetry/streamingtelemetryserver.csr \
  -CA /etc/sonic/telemetry/dsmsroot.cer -CAkey /etc/sonic/telemetry/dsmsroot.key \
  -CAcreateserial -out /etc/sonic/telemetry/streamingtelemetryserver.cer \
  -days 365 -sha512
```

Restart `telemtry` container:
```
admin@sonic:~$ sudo docker container restart telemetry
telemetry

$ sudo docker container ls
CONTAINER ID   IMAGE                                COMMAND                  CREATED       STATUS         PORTS     NAMES
41b1a5310be9   docker-sonic-telemetry:latest        "/usr/local/bin/supe…"   3 hours ago   Up 9 minutes             telemetry
```

Copy the created server and CA certificate to local host with pygnmi:
```
+--certs
   +--ca.pem (on SONiC it was /etc/sonic/telemetry/dsmsroot.cer)
   +--server.pem (on SONiC it was /etc/sonic/telemetry/streamingtelemetryserver.cer)
   +--server.key (on SONiC it was /etc/sonic/telemetry/streamingtelemetryserver.key)
```

Then create a script with pygnmi, but provide the paths to 3 aforementioned artefacts:
```
# Modules
from pygnmi.client import gNMIclient
import json


# Variables
host = {
    "ip_address": "192.168.101.17",
    "port": 50051,
    "username": "admin",
    "password": "YourPaSsWoRd",
}

# Body
if __name__ == "__main__":
    paths = ["/openconfig-interfaces:interfaces/interface"]
    with gNMIclient(
        target=(host["ip_address"], host["port"]),
        username=host["username"],
        password=host["password"],
        path_root="certs/ca.pem",
        path_cert="certs/server.pem",
        path_key="certs/server.key",
        override="dev-pygnmi-sonic-003",
    ) as gc:
        result = gc.capabilities()
        print(json.dumps(result, indent=4))
```
I use override here to match the CN from the certificate. Alternatively, you can amend the `/etc/hosts` to include the IP for CN.

Running finally the script:
```
# python test.py 
{
    "supported_models": [
        {
            "name": "openconfig-acl",
            "organization": "OpenConfig working group",
            "version": "1.0.2"
        },
        {
            "name": "openconfig-acl",
            "organization": "OpenConfig working group",
            "version": "1.0.2"
        },
        {
            "name": "openconfig-interfaces",
            "organization": "OpenConfig working group",
            "version": "1.0.2"
        },
        {
            "name": "openconfig-lldp",
            "organization": "OpenConfig working group",
            "version": "1.0.2"
        },
        {
            "name": "openconfig-platform",
            "organization": "OpenConfig working group",
            "version": "1.0.2"
        },
        {
            "name": "openconfig-system",
            "organization": "OpenConfig working group",
            "version": "1.0.2"
        },
        {
            "name": "ietf-yang-library",
            "organization": "IETF NETCONF (Network Configuration) Working Group",
            "version": "2016-06-21"
        },
        {
            "name": "sonic-db",
            "organization": "SONiC",
            "version": "0.1.0"
        }
    ],
    "supported_encodings": [
        "json",
        "json_ietf"
    ],
    "gnmi_version": "0.7.0"
}
```
Please, give a go and let me know

**Comment by KasinathAviz** [comment]
Sure I will try and update.

<https://aviznetworks.com/>

Kasinath Rajendran

Member, Technical Staff

+91 974-254-5247

***@***.***

aviznetworks.com

[image: linkedin.png]
<https://www.linkedin.com/company/aviz-networks/>    [image:
twitter.png] <https://twitter.com/aviznetworks>    [image: youtube.png]
<https://www.youtube.com/channel/UCS0o0Lwv5M893eGpfAdOBNA>

**Comment by XioNoX** [comment]
Thanks, I finally got it to work. Many things changed, but here I'm using testing a more recent SONiC  OS (4.0.5) with updated doc. My (or one) issue I think was that SONiC was not picking up the certificates properly.

**Comment by JahedulAnowar** [comment]
Hi @akarneliuk , I am also getting the grpc timeout error:

I am using NEC Network OS based on Goldstone:
```
admin@necOS:~$ nos-show-platform-os
name    description               software-version
------  ------------------------  --------------------
nos-1   Network operating system  nec-network-os-1.2.8
```

```
admin@necOS:~$  uname -a
Linux necOS 5.4.47-Goldstone+ #1 SMP PREEMPT Wed Jul 26 18:17:14 UTC 2023 aarch64 GNU/Linux
````


Error:
```
python3 main.py 
Traceback (most recent call last):
  File "main.py", line 9, in <module>
    with gNMIclient(target=host, username='admin', password='my-password', insecure=True) as gc:
  File "/home/shd/.local/lib/python3.8/site-packages/pygnmi/client.py", line 136, in __enter__
    return self.connect()
  File "/home/shd/.local/lib/python3.8/site-packages/pygnmi/client.py", line 259, in connect
    self.wait_for_connect(timeout)
  File "/home/shd/.local/lib/python3.8/site-packages/pygnmi/client.py", line 281, in wait_for_connect
    grpc.channel_ready_future(self.__channel).result(timeout=timeout)
  File "/home/shd/.local/lib/python3.8/site-packages/grpc/_utilities.py", line 151, in result
    self._block(timeout)
  File "/home/shd/.local/lib/python3.8/site-packages/grpc/_utilities.py", line 97, in _block
    raise grpc.FutureTimeoutError()
grpc.FutureTimeoutError
``` 

Script:
```
# Modules
from pygnmi.client import gNMIclient

# Variables
host = ('192.168.100.100', 51052)

# Body
if __name__ == '__main__':
    with gNMIclient(target=host, username='admin', password='my-password', insecure=True) as gc:
        result = gc.capabilities()

    print(result)
```

I can get capabilities using `gnmic` from a linux terminal:
```
gnmic --config insecure.yml capabilities
gNMI version: 0.6.0
supported models:
  - openconfig-types, OpenConfig working group, 2019-04-16
  - openconfig-yang-types, OpenConfig working group, 2021-07-14
  - openconfig-extensions, OpenConfig working group, 2020-06-16
  - openconfig-interfaces, OpenConfig working group, 2021-04-06
  - openconfig-if-ethernet, OpenConfig working group, 2022-04-20
  - openconfig-if-types, OpenConfig working group, 2018-11-21
  - iana-if-type, IANA, 2017-01-19
  - openconfig-platform, OpenConfig working group, 2022-06-10
  - openconfig-platform-types, OpenConfig working group, 2022-03-27
  - openconfig-platform-linecard, OpenConfig working group, 2022-04-21
  - openconfig-platform-port, OpenConfig working group, 2021-10-01
  - openconfig-platform-transceiver, OpenConfig working group, 2021-07-29
  - openconfig-platform-fan, OpenConfig working group, 2018-11-21
  - openconfig-platform-psu, OpenConfig working group, 2018-11-21
  - openconfig-platform-cpu, OpenConfig working group, 2018-11-21
  - openconfig-terminal-device, OpenConfig working group, 2021-07-29
  - openconfig-transport-types, OpenConfig working group, 2021-07-29
  - openconfig-transport-line-common, OpenConfig working group, 2019-06-03
  - openconfig-system, OpenConfig working group, 2021-07-20
  - openconfig-system-terminal, OpenConfig working group, 2018-11-21
  - openconfig-telemetry, OpenConfig working group, 2018-11-21
  - openconfig-telemetry-types, OpenConfig working group, 2018-11-21
  - openconfig-terminal-device-properties, OpenConfig working group, 2022-04-26
  - openconfig-terminal-device-property-types, OpenConfig working group, 2022-03-08
  - openconfig-alarms, OpenConfig working group, 2019-07-09
  - openconfig-alarm-types, OpenConfig working group, 2018-11-21
  - ietf-alarms, IETF CCAMP Working Group, 2019-09-11
  - nec-optical-alarm-type-id, NEC Corporation, 2023-01-16
  - nec-optical-openconfig-alarms-notifications, NEC Corporation, 2022-12-05
  - nec-optical-openconfig-system-snmp, NEC Corporation, 2022-10-01
  - nec-optical-openconfig-system-config, NEC Corporation, 2022-11-16
  - nec-optical-openconfig-platform-led, NEC Corporation, 2022-10-01
  - nec-optical-openconfig-platform-fan, NEC Corporation, 2022-10-01
  - nec-optical-openconfig-platform-sensor, NEC Corporation, 2022-10-01
  - nec-optical-openconfig-platform-storage, NEC Corporation, 2022-10-01
  - nec-optical-openconfig-platform-fabric, NEC Corporation, 2022-10-01
  - nec-optical-openconfig-platform-optical-channel, NEC Corporation, 2022-12-02
  - nec-optical-openconfig-terminal-device, NEC Corporation, 2023-01-16
  - nec-optical-openconfig-interfaces, NEC Corporation, 2022-10-01
  - nec-optical-openconfig-openflow-deviations, NEC Corporation, 2022-10-01
  - nec-optical-openconfig-platform-cpu-deviations, NEC Corporation, 2022-10-01
  - nec-optical-openconfig-platform-linecard-deviations, NEC Corporation, 2022-10-01
  - nec-optical-openconfig-platform-psu-deviations, NEC Corporation, 2022-10-01
  - nec-optical-openconfig-platform-deviations, NEC Corporation, 2022-10-01
  - nec-optical-openconfig-system-deviations, NEC Corporation, 2023-01-16
supported encodings:
  - JSON
```

Thank you.

**Comment by unknownuser83** [comment]
> Hello @rkasinath ,
> 
> gRPC timeout failure means that `pygnmi` is not able to connect to the host. Here are a few consideration:
> 
> * `insecure=True` means that that gNMI is configured on the server (your network switch) in a way that it doesn't use encryption. That is not `--skip-verify`. If your host uses self-signed certificate, you shall use `skip_verify=True` instead. Refer to [the skip_verify demo](https://www.youtube.com/watch?v=-r4JbQBjVGU)
> * You don't specify host, where are connecting to. You have "" instead of IP address of FQDN. Please, specify it, even if it is 127.0.0.1 or localhost. Connection to Unix socket is also supported, but you need to specify that as will.
> 
> Please, test and let me know.
> 
> Best, Anton

Hi @akarneliuk ,
         I am Mathavan from Palc networks and i am trying to connect sonic-net/sonic-telemetry.git server by using pygnmi but got issues while installing pygnmi inside the sonic-telemetry docker container what should i do to solve this issues

**Comment by miguecor** [comment]
I know this is an old post, but I'm experiencing this issue with Cisco Nexus 9300 switches.

This is my code:
```python
[some lines ommitted]
with gNMIclient(target=host, username=USR, password=PWD, insecure=True) as gc:
    result = gc.capabilities()
print(result)
```

When I run this code, I get the following errors:
```shell
Traceback (most recent call last):
  File "/Users/user123/python/pygnmi/main.py", line 32, in <module>
    with gNMIclient(target=host, username=USERNAME, password=PASSWORD, insecure=True) as gc:
  File "/Users/user123/.pyenv/versions/pygnmi-client/lib/python3.11/site-packages/pygnmi/client.py", line 143, in __enter__
    return self.connect()
           ^^^^^^^^^^^^^^
  File "/Users/user123/.pyenv/versions/pygnmi-client/lib/python3.11/site-packages/pygnmi/client.py", line 291, in connect
    self.wait_for_connect(timeout)
  File "/Users/user123/.pyenv/versions/pygnmi-client/lib/python3.11/site-packages/pygnmi/client.py", line 313, in wait_for_connect
    grpc.channel_ready_future(self.__channel).result(timeout=timeout)
  File "/Users/user123/.pyenv/versions/pygnmi-client/lib/python3.11/site-packages/grpc/_utilities.py", line 162, in result
    self._block(timeout)
  File "/Users/user123/.pyenv/versions/pygnmi-client/lib/python3.11/site-packages/grpc/_utilities.py", line 106, in _block
    raise grpc.FutureTimeoutError()
grpc.FutureTimeoutError

Process finished with exit code 1
```

When I try with the `skip_verify=True` option instead of `insecure=True`, I get the following error:
```shell
Traceback (most recent call last):
  File "/Users/user123/.pyenv/versions/pygnmi-client/lib/python3.11/site-packages/pygnmi/client.py", line 202, in connect
    ssl_cert = ssl.get_server_certificate((self.__target[0], self.__target[1])).encode("utf-8")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user123/.pyenv/versions/3.11.7/lib/python3.11/ssl.py", line 1564, in get_server_certificate
    with create_connection(addr, timeout=timeout) as sock:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user123/.pyenv/versions/3.11.7/lib/python3.11/socket.py", line 827, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user123/.pyenv/versions/3.11.7/lib/python3.11/socket.py", line 962, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/user123/python/pygnmi/main.py", line 32, in <module>
    with gNMIclient(target=host, username=USR, password=PWD, skip_verify=True) as gc:
  File "/Users/user123/.pyenv/versions/pygnmi-client/lib/python3.11/site-packages/pygnmi/client.py", line 143, in __enter__
    return self.connect()
           ^^^^^^^^^^^^^^
  File "/Users/user123/.pyenv/versions/pygnmi-client/lib/python3.11/site-packages/pygnmi/client.py", line 206, in connect
    raise gNMIException(
pygnmi.client.gNMIException: The SSL certificate cannot be retrieved from ('admin', 'password123')
```

But when I use the `gnmic` tool, I get the following output:
```shell
❯ gnmic -a 192.168.1.100:50051 -u 'admin' -p 'password.123' --skip-verify capabilities
---
gNMI version: 0.5.0
supported models:
  - Cisco-NX-OS-device, Cisco Systems, Inc., 2022-10-25
  - DME, Cisco Systems, Inc.,
  - Cisco-NX-OS-Syslog-oper, Cisco Systems, Inc., 2019-08-15
supported encodings:
  - JSON
  - PROTO
```

Could you please provide some guidance?  Thanks!
